A = int(input())
B = int(input())
C = int(input())
result =A*B*C
r=[int(r) for r in str(result)]
zero =filter(lambda x: x==0,r)
print(len(list(zero)))
one = filter(lambda x:x==1,r)
print(len(list(one)))
two =filter(lambda x:x==2,r)
print(len(list(two)))
three =filter(lambda x:x==3,r)
print(len(list(three)))
four =filter(lambda x:x==4,r)
print(len(list(four)))
five = filter(lambda x:x==5,r)
print(len(list(five)))
six= filter(lambda x:x==6,r)
print(len(list(six)))
seven=filter(lambda x:x==7,r)
print(len(list(seven)))
eight =filter(lambda x:x==8,r)
print(len(list(eight)))
nine= filter(lambda x:x==9,r)
print(len(list(nine)))
